spring:
  data:
    mongodb:
      auto-index-creation: true
  application:
    name: contactBookApp
jwt:
  secret: ${JWT_SECRET:GS1JfaQxVlZROFO82tOIoRmg7p1il57R0ChmGp8sycuVpmABRawFDNgad0kwAQ}
  tokenValidity: ${JWT_TOKEN_VALIDITY:86400}